name: CI workflow for python app
on:
  push:
    branches:
      - "main"
#creating jobs
jobs:
  rajk-python-app-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
    steps:
      - name : checking python version 
        run: python -V

      - name: fetching git repo code torunner machine
        uses: actions/checkout@v4
        
      - name: lets run python code on ${{ matrix.os }}
        run: python rajk.py